package com.wo56.business.route.vo;
// default package
// Generated 2016-8-1 17:28:05 by Hibernate Tools 3.2.2.GA

/**
 * RouteIntroduce generated by hbm2java
 */
public class RouteIntroduce implements java.io.Serializable {

	/**   
	 * 线路配置ID.  
	 */
	private Long cfgId;

	/**   
	 * 起始省份ID.  
	 */
	private Long sourceProvinceId;

	/**   
	 * 起始省份名.  
	 */
	private String sourceProvinceName;

	/**   
	 * 起始城市ID.  
	 */
	private Long sourceCityId;

	/**   
	 * 起始城市名.  
	 */
	private String sourceCityName;

	/**   
	 * 起始县区ID.  
	 */
	private Long sourceCountyId;

	/**   
	 * 起始县区名.  
	 */
	private String sourceCountyName;

	/**   
	 * 起始乡/镇/街道/ID.  
	 */
	private Long sourceTownId;

	/**   
	 * 起始乡/镇/街道名称.  
	 */
	private String sourceTownName;

	/**   
	 * 目的省份ID.  
	 */
	private Long desProvinceId;

	/**   
	 * 目的省份名.  
	 */
	private String desProvinceName;

	/**   
	 * 目的城市ID.  
	 */
	private Long desCityId;

	/**   
	 * 目的城市名.  
	 */
	private String desCityName;

	/**   
	 * 目的县区ID.  
	 */
	private Long desCountyId;

	/**   
	 * 目的县区名.  
	 */
	private String desCountyName;

	/**   
	 * 目的乡/镇/街道/ID.  
	 */
	private Long desTownId;

	/**   
	 * 目的乡/镇/街道名称.  
	 */
	private String desTownName;

	/**   
	 * 归属组织ID.  
	 */
	private Long orgId;

	/**   
	 * 租户ID.  
	 */
	private Long tenantId;

	/**   
	 * 租户CODE.  
	 */
	private String tenantCode;

	/**   
	 * 起始地区简介.  
	 */
	private String sourceDetail;

	/**   
	 * 目的地区简介.  
	 */
	private String desDetail;

	public RouteIntroduce() {
	}

	public RouteIntroduce(Long tenantId, String tenantCode) {
		this.tenantId = tenantId;
		this.tenantCode = tenantCode;
	}

	public RouteIntroduce(Long sourceProvinceId, String sourceProvinceName,
			Long sourceCityId, String sourceCityName, Long sourceCountyId,
			String sourceCountyName, Long sourceTownId, String sourceTownName,
			Long desProvinceId, String desProvinceName, Long desCityId,
			String desCityName, Long desCountyId, String desCountyName,
			Long desTownId, String desTownName, Long orgId, Long tenantId,
			String tenantCode, String sourceDetail, String desDetail) {
		this.sourceProvinceId = sourceProvinceId;
		this.sourceProvinceName = sourceProvinceName;
		this.sourceCityId = sourceCityId;
		this.sourceCityName = sourceCityName;
		this.sourceCountyId = sourceCountyId;
		this.sourceCountyName = sourceCountyName;
		this.sourceTownId = sourceTownId;
		this.sourceTownName = sourceTownName;
		this.desProvinceId = desProvinceId;
		this.desProvinceName = desProvinceName;
		this.desCityId = desCityId;
		this.desCityName = desCityName;
		this.desCountyId = desCountyId;
		this.desCountyName = desCountyName;
		this.desTownId = desTownId;
		this.desTownName = desTownName;
		this.orgId = orgId;
		this.tenantId = tenantId;
		this.tenantCode = tenantCode;
		this.sourceDetail = sourceDetail;
		this.desDetail = desDetail;
	}

	public Long getCfgId() {
		return this.cfgId;
	}

	public void setCfgId(Long cfgId) {
		this.cfgId = cfgId;
	}

	public Long getSourceProvinceId() {
		return this.sourceProvinceId;
	}

	public void setSourceProvinceId(Long sourceProvinceId) {
		this.sourceProvinceId = sourceProvinceId;
	}

	public String getSourceProvinceName() {
		return this.sourceProvinceName;
	}

	public void setSourceProvinceName(String sourceProvinceName) {
		this.sourceProvinceName = sourceProvinceName;
	}

	public Long getSourceCityId() {
		return this.sourceCityId;
	}

	public void setSourceCityId(Long sourceCityId) {
		this.sourceCityId = sourceCityId;
	}

	public String getSourceCityName() {
		return this.sourceCityName;
	}

	public void setSourceCityName(String sourceCityName) {
		this.sourceCityName = sourceCityName;
	}

	public Long getSourceCountyId() {
		return this.sourceCountyId;
	}

	public void setSourceCountyId(Long sourceCountyId) {
		this.sourceCountyId = sourceCountyId;
	}

	public String getSourceCountyName() {
		return this.sourceCountyName;
	}

	public void setSourceCountyName(String sourceCountyName) {
		this.sourceCountyName = sourceCountyName;
	}

	public Long getSourceTownId() {
		return this.sourceTownId;
	}

	public void setSourceTownId(Long sourceTownId) {
		this.sourceTownId = sourceTownId;
	}

	public String getSourceTownName() {
		return this.sourceTownName;
	}

	public void setSourceTownName(String sourceTownName) {
		this.sourceTownName = sourceTownName;
	}

	public Long getDesProvinceId() {
		return this.desProvinceId;
	}

	public void setDesProvinceId(Long desProvinceId) {
		this.desProvinceId = desProvinceId;
	}

	public String getDesProvinceName() {
		return this.desProvinceName;
	}

	public void setDesProvinceName(String desProvinceName) {
		this.desProvinceName = desProvinceName;
	}

	public Long getDesCityId() {
		return this.desCityId;
	}

	public void setDesCityId(Long desCityId) {
		this.desCityId = desCityId;
	}

	public String getDesCityName() {
		return this.desCityName;
	}

	public void setDesCityName(String desCityName) {
		this.desCityName = desCityName;
	}

	public Long getDesCountyId() {
		return this.desCountyId;
	}

	public void setDesCountyId(Long desCountyId) {
		this.desCountyId = desCountyId;
	}

	public String getDesCountyName() {
		return this.desCountyName;
	}

	public void setDesCountyName(String desCountyName) {
		this.desCountyName = desCountyName;
	}

	public Long getDesTownId() {
		return this.desTownId;
	}

	public void setDesTownId(Long desTownId) {
		this.desTownId = desTownId;
	}

	public String getDesTownName() {
		return this.desTownName;
	}

	public void setDesTownName(String desTownName) {
		this.desTownName = desTownName;
	}

	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public Long getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(Long tenantId) {
		this.tenantId = tenantId;
	}

	public String getTenantCode() {
		return this.tenantCode;
	}

	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	public String getSourceDetail() {
		return this.sourceDetail;
	}

	public void setSourceDetail(String sourceDetail) {
		this.sourceDetail = sourceDetail;
	}

	public String getDesDetail() {
		return this.desDetail;
	}

	public void setDesDetail(String desDetail) {
		this.desDetail = desDetail;
	}

}
