package com.wo56.business.cm.vo;

// Generated 2016-3-8 16:39:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CmAccountInfo generated by hbm2java
 */
public class CmAccountInfo implements java.io.Serializable {

	private long accountId;
	private long userId;
	private String accountPwd;
	private Date modPwdTime;
	private long balance;
	private int accountType;
	private String remark;
	private long orgId;
	private long tenantId;
	private long opId;
	private Date createTime;

	public CmAccountInfo() {
	}

	public CmAccountInfo(long userId, long balance, int accountType,
			String remark, long orgId, long tenantId, long opId, Date createTime) {
		this.userId = userId;
		this.balance = balance;
		this.accountType = accountType;
		this.remark = remark;
		this.orgId = orgId;
		this.tenantId = tenantId;
		this.opId = opId;
		this.createTime = createTime;
	}

	public CmAccountInfo(long userId, String accountPwd, Date modPwdTime,
			long balance, int accountType, String remark, long orgId,
			long tenantId, long opId, Date createTime) {
		this.userId = userId;
		this.accountPwd = accountPwd;
		this.modPwdTime = modPwdTime;
		this.balance = balance;
		this.accountType = accountType;
		this.remark = remark;
		this.orgId = orgId;
		this.tenantId = tenantId;
		this.opId = opId;
		this.createTime = createTime;
	}

	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getAccountPwd() {
		return this.accountPwd;
	}

	public void setAccountPwd(String accountPwd) {
		this.accountPwd = accountPwd;
	}

	public Date getModPwdTime() {
		return this.modPwdTime;
	}

	public void setModPwdTime(Date modPwdTime) {
		this.modPwdTime = modPwdTime;
	}

	public long getBalance() {
		return this.balance;
	}

	public void setBalance(long balance) {
		this.balance = balance;
	}

	public int getAccountType() {
		return this.accountType;
	}

	public void setAccountType(int accountType) {
		this.accountType = accountType;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(long orgId) {
		this.orgId = orgId;
	}

	public long getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(long tenantId) {
		this.tenantId = tenantId;
	}

	public long getOpId() {
		return this.opId;
	}

	public void setOpId(long opId) {
		this.opId = opId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
