package com.wo56.business.cm.vo;

// Generated 2016-6-1 13:46:15 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CmSfUserOrgRel generated by hbm2java
 */
public class CmUserOrgRel implements java.io.Serializable {

	private long userOrgRelId;
	private Long userId;
	private Long orgId;
	private Long tenantId;
	private Long opId;
	private Date opDate;
	private Long marginFee;
	private Long marginFeeLimit;
	private Integer largestAcceptOrder;
	
	
	

	
	public Long getMarginFee() {
		return marginFee;
	}

	public void setMarginFee(Long marginFee) {
		this.marginFee = marginFee;
	}

	public Long getMarginFeeLimit() {
		return marginFeeLimit;
	}

	public void setMarginFeeLimit(Long marginFeeLimit) {
		this.marginFeeLimit = marginFeeLimit;
	}

	public Integer getLargestAcceptOrder() {
		return largestAcceptOrder;
	}

	public void setLargestAcceptOrder(Integer largestAcceptOrder) {
		this.largestAcceptOrder = largestAcceptOrder;
	}

	public long getUserOrgRelId() {
		return this.userOrgRelId;
	}

	public void setUserOrgRelId(long userOrgRelId) {
		this.userOrgRelId = userOrgRelId;
	}

	

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public Long getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(Long tenantId) {
		this.tenantId = tenantId;
	}

	public Long getOpId() {
		return this.opId;
	}

	public void setOpId(Long opId) {
		this.opId = opId;
	}

	public Date getOpDate() {
		return this.opDate;
	}

	public void setOpDate(Date opDate) {
		this.opDate = opDate;
	}

	
}
