package com.wo56.business.cm.vo;

// Generated 2016-5-31 11:23:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CmUserInfo generated by hbm2java
 */
public class CmUserInfo implements java.io.Serializable {

	private long userId;
	private Integer userType;
	private String loginAcct;
	private String loginPwd;
	private String userName;
	private Integer state;
//	private String orgCode;
//	private Long orgId;
	private Long opId;
	private Date createTime;
	private String dataSource;
	private Integer loginType;
	private String userPic;//头像
	private String openId;
	private Integer channelType;
	
	
	
	
	public String getOpenId() {
		return openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	public Integer getChannelType() {
		return channelType;
	}

	public void setChannelType(Integer channelType) {
		this.channelType = channelType;
	}

	public String getUserPic() {
		return userPic;
	}

	public void setUserPic(String userPic) {
		this.userPic = userPic;
	}

	public CmUserInfo() {
	}

	public CmUserInfo(long userId) {
		this.userId = userId;
	}

	public CmUserInfo(long userId, Integer userType, String loginAcct,
			String loginPwd, String userName, Integer state,  Long opId,
			Date createTime, Date updateTime, Integer isLogin,
			String userPhone, String dataSource) {
		this.userId = userId;
		this.userType = userType;
		this.loginAcct = loginAcct;
		this.loginPwd = loginPwd;
		this.userName = userName;
		this.state = state;
//		this.orgCode = orgCode;
//		this.orgId = orgId;
//		this.tenantId = tenantId;
//		this.tenantCode = tenantCode;
		this.opId = opId;
		this.createTime = createTime;
		this.dataSource = dataSource;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	public String getLoginAcct() {
		return this.loginAcct;
	}

	public void setLoginAcct(String loginAcct) {
		this.loginAcct = loginAcct;
	}

	public String getLoginPwd() {
		return this.loginPwd;
	}

	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Long getOpId() {
		return this.opId;
	}

	public void setOpId(Long opId) {
		this.opId = opId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	public Integer getLoginType() {
		return loginType;
	}

	public void setLoginType(Integer loginType) {
		this.loginType = loginType;
	}

	
}
