package com.wo56.business.ord.vo;

import com.framework.core.base.POJO;

// Generated 2016-3-15 16:26:20 by Hibernate Tools 3.4.0.CR1

/**
 * OrdDepartDetailId generated by hbm2java
 */
public class OrdDepartDetailId extends POJO implements java.io.Serializable {

	private long batchNum;
	private long orderId;

	public OrdDepartDetailId() {
	}

	public OrdDepartDetailId(long batchNum, long orderId) {
		this.batchNum = batchNum;
		this.orderId = orderId;
	}

	public long getBatchNum() {
		return this.batchNum;
	}

	public void setBatchNum(long batchNum) {
		this.batchNum = batchNum;
	}

	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdDepartDetailId))
			return false;
		OrdDepartDetailId castOther = (OrdDepartDetailId) other;

		return (this.getBatchNum() == castOther.getBatchNum())
				&& (this.getOrderId() == castOther.getOrderId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getBatchNum();
		result = 37 * result + (int) this.getOrderId();
		return result;
	}

}
