package com.wo56.common.sms.vo;

// Generated 2014-2-23 13:57:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.framework.core.base.POJO;

/**
 * SysSmsTemplate generated by hbm2java
 */
public class SysSmsTemplate extends POJO implements java.io.Serializable {

	private long templateId;
	private String templateName;
	private String templateContent;
	private Integer state;
	//private Date createDate;
	private String remarks;
	private String smsClassName;
	private String smsClassMethod;
	private Integer smsPerform;
	private Integer smsType;
	private String objType;
    private Long objId;
	

	public String getObjType() {
		return objType;
	}

	public void setObjType(String objType) {
		this.objType = objType;
	}

	public Long getObjId() {
		return objId;
	}

	public void setObjId(Long objId) {
		this.objId = objId;
	}

	public Integer getSmsType() {
		return smsType;
	}

	public void setSmsType(Integer smsType) {
		this.smsType = smsType;
	}

	public SysSmsTemplate() {
	}

	public SysSmsTemplate(long templateId, String templateName,
			String templateContent) {
		this.templateId = templateId;
		this.templateName = templateName;
		this.templateContent = templateContent;
	}

	public SysSmsTemplate(long templateId, String templateName,
			String templateContent, Integer state, Date createDate,
			String remarks,String smsClassName,String smsClassMethod,Integer smsPerform) {
		this.templateId = templateId;
		this.templateName = templateName;
		this.templateContent = templateContent;
		this.state = state;
		this.createDate = createDate;
		this.remarks = remarks;
		this.smsClassName = smsClassName;
		this.smsClassMethod = smsClassMethod;
		this.smsPerform = smsPerform;
	}

	public long getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(long templateId) {
		this.templateId = templateId;
	}

	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	public String getTemplateContent() {
		return this.templateContent;
	}

	public void setTemplateContent(String templateContent) {
		this.templateContent = templateContent;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	public String getSmsClassName() {
		return smsClassName;
	}

	public void setSmsClassName(String smsClassName) {
		this.smsClassName = smsClassName;
	}

	public String getSmsClassMethod() {
		return smsClassMethod;
	}

	public void setSmsClassMethod(String smsClassMethod) {
		this.smsClassMethod = smsClassMethod;
	}

	public Integer getSmsPerform() {
		return smsPerform;
	}

	public void setSmsPerform(Integer smsPerform) {
		this.smsPerform = smsPerform;
	}

}
