package com.wo56.business.sche.timeout.vo;

// default package
// Generated 2016-6-7 19:48:20 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.framework.core.util.SysStaticDataUtil;

/**
 * WayTimeOutDtl generated by hbm2java
 */
public class WayTimeOutDtl implements java.io.Serializable {

	private Long id;

	/**   
	 * 处理人id.  
	 */
	private Long dealId;

	/**   
	 * 处理人名称.  
	 */
	private String dealName;

	/**   
	 * 处理意见.  
	 */
	private String dealIdea;

	/**   
	 * 创建时间.  
	 */
	private Date createTime;

	/**   
	 * 处理状态.  
	 */
	private Integer dealState;
	private String dealStateName;
	private Long timeOutId;
	
	

	public Long getTimeOutId() {
		return timeOutId;
	}

	public void setTimeOutId(Long timeOutId) {
		this.timeOutId = timeOutId;
	}

	public void setDealState(Integer dealState) {
		this.dealState = dealState;
	}

	/**   
	 * 1    有效  2 无效.  
	 */
	private Integer sts;
	

	public String getDealStateName() {
		if(dealState>0){
			setDealStateName(SysStaticDataUtil.getSysStaticDataCodeName("DEAL_STATE", dealState+""));
		}
		return dealStateName;
	}

	public void setDealStateName(String dealStateName) {
		this.dealStateName = dealStateName;
	}

	public WayTimeOutDtl() {
	}

	public WayTimeOutDtl(Long id, Long dealId, String dealName,
			String dealIdea, Date createTime) {
		this.id = id;
		this.dealId = dealId;
		this.dealName = dealName;
		this.dealIdea = dealIdea;
		this.createTime = createTime;
	}

	public WayTimeOutDtl(Long id, Long dealId, String dealName,
			String dealIdea, Date createTime, Integer dealState, Integer sts) {
		this.id = id;
		this.dealId = dealId;
		this.dealName = dealName;
		this.dealIdea = dealIdea;
		this.createTime = createTime;
		this.dealState = dealState;
		this.sts = sts;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getDealId() {
		return this.dealId;
	}

	public void setDealId(Long dealId) {
		this.dealId = dealId;
	}

	public String getDealName() {
		return this.dealName;
	}

	public void setDealName(String dealName) {
		this.dealName = dealName;
	}

	public String getDealIdea() {
		return this.dealIdea;
	}

	public void setDealIdea(String dealIdea) {
		this.dealIdea = dealIdea;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getDealState() {
		return this.dealState;
	}

	public void setDealSatte(Integer dealState) {
		this.dealState = dealState;
	}

	public Integer getSts() {
		return this.sts;
	}

	public void setSts(Integer sts) {
		this.sts = sts;
	}

}
