package com.wo56.business.sche.timeout.vo;

// default package
// Generated 2016-6-7 19:48:20 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.framework.core.util.SysStaticDataUtil;

/**
 * WayTimeOut generated by hbm2java
 */
public class WayTimeOut implements java.io.Serializable {

	private Long timeOutId;

	/**   
	 * 运单号.  
	 */
	private String wayBillMain;

	/**   
	 * 服务类型.  
	 */
	private String serverType;

	/**   
	 * 超时类型 1 干线结束超时 2 预约超时 3 签收超时.  
	 */
	private Integer timeOueType;

	private Date startTime;

	private Date endTime;

	private String timeLimit;

	private int dealState;
	private String dealStateName;

	/**   
	 * 租户id.  
	 */
	private String tenantId;

	/**   
	 * 租户编码.  
	 */
	private String tenantCode;

	/**   
	 * 数据有效性 1  有效 2 无效.  
	 */
	private Integer sts;

	private Date createTime;
	private String timeOutTypeName;
	private Long taskId;
	/**订单id*/
	private Long orderId;
	
	
	
	
	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public Long getTaskId() {
		return taskId;
	}

	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	public String getTimeOutTypeName() {
		if(timeOueType!=null){
			setTimeOutTypeName(SysStaticDataUtil.getSysStaticDataCodeName("TIME_OUT_TYPE", timeOueType+""));
		}
		return timeOutTypeName;
	}

	public void setTimeOutTypeName(String timeOutTypeName) {
		this.timeOutTypeName = timeOutTypeName;
	}

	public String getDealStateName() {
		if(dealState>0){
			setDealStateName(SysStaticDataUtil.getSysStaticDataCodeName("DEAL_STATE", dealState+""));
		}
		return dealStateName;
	}

	public void setDealStateName(String dealStateName) {
		this.dealStateName = dealStateName;
	}

	public WayTimeOut() {
	}

	public WayTimeOut(String wayBillMain, String serverType, int dealState,
			String tenantId, Date createTime) {
		this.wayBillMain = wayBillMain;
		this.serverType = serverType;
		this.dealState = dealState;
		this.tenantId = tenantId;
		this.createTime = createTime;
	}

	public WayTimeOut(String wayBillMain, String serverType,
			Integer timeOueType, Date startTime, Date endTime,
			String timeLimit, int dealState, String tenantId, String tenantCode,
			Integer sts, Date createTime) {
		this.wayBillMain = wayBillMain;
		this.serverType = serverType;
		this.timeOueType = timeOueType;
		this.startTime = startTime;
		this.endTime = endTime;
		this.timeLimit = timeLimit;
		this.dealState = dealState;
		this.tenantId = tenantId;
		this.tenantCode = tenantCode;
		this.sts = sts;
		this.createTime = createTime;
	}

	public Long getTimeOutId() {
		return this.timeOutId;
	}

	public void setTimeOutId(Long timeOutId) {
		this.timeOutId = timeOutId;
	}

	public String getWayBillMain() {
		return this.wayBillMain;
	}

	public void setWayBillMain(String wayBillMain) {
		this.wayBillMain = wayBillMain;
	}

	public String getServerType() {
		return this.serverType;
	}

	public void setServerType(String serverType) {
		this.serverType = serverType;
	}

	public Integer getTimeOueType() {
		return this.timeOueType;
	}

	public void setTimeOueType(Integer timeOueType) {
		this.timeOueType = timeOueType;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getTimeLimit() {
		return this.timeLimit;
	}

	public void setTimeLimit(String timeLimit) {
		this.timeLimit = timeLimit;
	}

	public int getDealState() {
		return this.dealState;
	}

	public void setDealState(int dealState) {
		this.dealState = dealState;
	}

	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public String getTenantCode() {
		return this.tenantCode;
	}

	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	public Integer getSts() {
		return this.sts;
	}

	public void setSts(Integer sts) {
		this.sts = sts;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
