package com.wo56.business.ac.vo;
// default package
// Generated 2016-3-21 10:21:29 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * CmAccount generated by hbm2java
 */
public class AcAccount implements java.io.Serializable {

	/**   
	 * 账户ID.  
	 */
	private Long accountId;

	/**   
	 * 帐户网点类型1、网点账户2、用户账户.  
	 */
	private int objType;

	/**   
	 * 对象id.  
	 */
	private Long objId;

	/**   
	 * 账户类型:1现金账户2平台账户3押金账户.  
	 */
	private Integer accountType;

	/**   
	 * 账户密码.  
	 */
	private String accountPwd;

	/**   
	 * 修改密码时间.  
	 */
	private Date modPwdTime;

	/**   
	 * 账户余额。单位分.  
	 */
	private Long balance;

	/**   
	 * 操作员ID.  
	 */
	private Long opId;

	/**   
	 * 创建时间.  
	 */
	private Date createTime;

	/**   
	 * 备注.  
	 */
	private String remark;

	public AcAccount() {
	}

	public AcAccount(int objType, Long objId, Long balance, Long opId,
			Date createTime) {
		this.objType = objType;
		this.objId = objId;
		this.balance = balance;
		this.opId = opId;
		this.createTime = createTime;
	}

	public AcAccount(int objType, Long objId, Integer accountType,
			String accountPwd, Date modPwdTime, Long balance, Long opId,
			Date createTime, String remark) {
		this.objType = objType;
		this.objId = objId;
		this.accountType = accountType;
		this.accountPwd = accountPwd;
		this.modPwdTime = modPwdTime;
		this.balance = balance;
		this.opId = opId;
		this.createTime = createTime;
		this.remark = remark;
	}

	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	public int getObjType() {
		return this.objType;
	}

	public void setObjType(int objType) {
		this.objType = objType;
	}

	public Long getObjId() {
		return this.objId;
	}

	public void setObjId(Long objId) {
		this.objId = objId;
	}

	public Integer getAccountType() {
		return this.accountType;
	}

	public void setAccountType(Integer accountType) {
		this.accountType = accountType;
	}

	public String getAccountPwd() {
		return this.accountPwd;
	}

	public void setAccountPwd(String accountPwd) {
		this.accountPwd = accountPwd;
	}

	public Date getModPwdTime() {
		return this.modPwdTime;
	}

	public void setModPwdTime(Date modPwdTime) {
		this.modPwdTime = modPwdTime;
	}

	public Long getBalance() {
		return this.balance;
	}

	public void setBalance(Long balance) {
		this.balance = balance;
	}

	public Long getOpId() {
		return this.opId;
	}

	public void setOpId(Long opId) {
		this.opId = opId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
