package com.wo56.business.ac.vo;

//Generated 2016-3-8 16:39:51 by Hibernate Tools 3.4.0.CR1


/**
* AcFeeConfig generated by hbm2java
*/
public class AcOrderFeeSummary implements java.io.Serializable {
	
	//交易类型:1现金2平台账户
	private int busiType;
	//支付状态1、未收2、已收3、已支4、未支
	private int paySts;
	//收支类型:1收入2支出
	private int payType;
	//费用类型
	private int feeType;
	//费用类型名称
	private String feeTypeName;
	//费用金额
	private long amount;
	//对象类型(1业务员、2客户ID、3网点)
	private int objType;
	//对象ID(业务员ID、客户ID、网点ID)
	private long objId;
	//对象名称
	private String objName;
	
	public String getObjName() {
		return objName;
	}
	public void setObjName(String objName) {
		this.objName = objName;
	}
	public int getBusiType() {
		return busiType;
	}
	public void setBusiType(int busiType) {
		this.busiType = busiType;
	}
	public int getPaySts() {
		return paySts;
	}
	public void setPaySts(int paySts) {
		this.paySts = paySts;
	}
	public int getPayType() {
		return payType;
	}
	public void setPayType(int payType) {
		this.payType = payType;
	}
	public int getFeeType() {
		return feeType;
	}
	public void setFeeType(int feeType) {
		this.feeType = feeType;
	}
	public String getFeeTypeName() {
		return feeTypeName;
	}
	public void setFeeTypeName(String feeTypeName) {
		this.feeTypeName = feeTypeName;
	}
	public long getAmount() {
		return amount;
	}
	public void setAmount(long amount) {
		this.amount = amount;
	}
	public int getObjType() {
		return objType;
	}
	public void setObjType(int objType) {
		this.objType = objType;
	}
	public long getObjId() {
		return objId;
	}
	public void setObjId(long objId) {
		this.objId = objId;
	}
 
}
