package com.wo56.business.sys.vo;
// default package
// Generated 2015-7-8 15:27:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SysEntity generated by hbm2java
 */
public class SysEntity implements java.io.Serializable {

	private int entityId;
	private String entityName;
	private int entityType;
	private int state;
	private Date createDate;
	private Date lastModifyDate;
	private Long lastModifyOperatorId;
	private String remark;

	public SysEntity() {
	}

	public SysEntity(int entityId, String entityName, int entityType,
			int state, Date createDate, Date lastModifyDate) {
		this.entityId = entityId;
		this.entityName = entityName;
		this.entityType = entityType;
		this.state = state;
		this.createDate = createDate;
		this.lastModifyDate = lastModifyDate;
	}

	public SysEntity(int entityId, String entityName, int entityType,
			int state, Date createDate, Date lastModifyDate,
			Long lastModifyOperatorId, String remark) {
		this.entityId = entityId;
		this.entityName = entityName;
		this.entityType = entityType;
		this.state = state;
		this.createDate = createDate;
		this.lastModifyDate = lastModifyDate;
		this.lastModifyOperatorId = lastModifyOperatorId;
		this.remark = remark;
	}

	public int getEntityId() {
		return this.entityId;
	}

	public void setEntityId(int entityId) {
		this.entityId = entityId;
	}

	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	public int getEntityType() {
		return this.entityType;
	}

	public void setEntityType(int entityType) {
		this.entityType = entityType;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Long getLastModifyOperatorId() {
		return this.lastModifyOperatorId;
	}

	public void setLastModifyOperatorId(Long lastModifyOperatorId) {
		this.lastModifyOperatorId = lastModifyOperatorId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Override
	public String toString() {
		return "SysEntity [entityId=" + entityId + ", entityName=" + entityName
				+ ", entityType=" + entityType + ", state=" + state
				+ ", createDate=" + createDate + ", lastModifyDate="
				+ lastModifyDate + ", lastModifyOperatorId="
				+ lastModifyOperatorId + ", remark=" + remark + "]";
	}
}
