package com.wo56.business.sys.vo;

// default package
// Generated 2015-7-9 8:45:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * SysMenu generated by hbm2java
 */
public class SysMenu implements java.io.Serializable {

	private int menuId;
	private String menuName;
	private int parentId;
	private long entityId;
	private String menuPath;
	private Integer menuSeq;
	private String menuIcon;
	private String domainCode;
	private String domainName;
	private int state;
	private Date createDate;
	private Date lastModifyDate;
	private Long lastModifyOperatorId;
	private String remark;

	private List<SysMenu> childMenus;
	private boolean isRoot;
	private boolean isLeaf;
	private String menuType;
	private boolean $$isChecked;

	public SysMenu() {
	}

	public SysMenu(int menuId, String menuName, int parentId, long entityId,
			String domainCode, int state) {
		this.menuId = menuId;
		this.menuName = menuName;
		this.parentId = parentId;
		this.entityId = entityId;
		this.domainCode = domainCode;
		this.state = state;
	}

	public SysMenu(int menuId, String menuName, int parentId, long entityId,
			String menuPath, Integer menuSeq, String menuIcon,
			String domainCode, String domainName, int state, Date createDate,
			Date lastModifyDate, Long lastModifyOperatorId, String remark) {
		this.menuId = menuId;
		this.menuName = menuName;
		this.parentId = parentId;
		this.entityId = entityId;
		this.menuPath = menuPath;
		this.menuSeq = menuSeq;
		this.menuIcon = menuIcon;
		this.domainCode = domainCode;
		this.domainName = domainName;
		this.state = state;
		this.createDate = createDate;
		this.lastModifyDate = lastModifyDate;
		this.lastModifyOperatorId = lastModifyOperatorId;
		this.remark = remark;
	}

	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public long getEntityId() {
		return this.entityId;
	}

	public void setEntityId(long entityId) {
		this.entityId = entityId;
	}

	public String getMenuPath() {
		return this.menuPath;
	}

	public void setMenuPath(String menuPath) {
		this.menuPath = menuPath;
	}

	public Integer getMenuSeq() {
		return this.menuSeq;
	}

	public void setMenuSeq(Integer menuSeq) {
		this.menuSeq = menuSeq;
	}

	public String getMenuIcon() {
		return this.menuIcon;
	}

	public void setMenuIcon(String menuIcon) {
		this.menuIcon = menuIcon;
	}

	public String getDomainCode() {
		return this.domainCode;
	}

	public void setDomainCode(String domainCode) {
		this.domainCode = domainCode;
	}

	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Long getLastModifyOperatorId() {
		return this.lastModifyOperatorId;
	}

	public void setLastModifyOperatorId(Long lastModifyOperatorId) {
		this.lastModifyOperatorId = lastModifyOperatorId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public List<SysMenu> getChildMenus() {
		return childMenus;
	}

	public void setChildMenus(List<SysMenu> childMenus) {
		this.childMenus = childMenus;
	}

	public boolean isRoot() {
		return isRoot;
	}

	public void setRoot(boolean isRoot) {
		this.isRoot = isRoot;
	}

	public boolean isLeaf() {
		return isLeaf;
	}

	public void setLeaf(boolean isLeaf) {
		this.isLeaf = isLeaf;
	}

	@Override
	public String toString() {
		return "SysMenu [menuId=" + menuId + ", menuName=" + menuName
				+ ", parentId=" + parentId + ", entityId=" + entityId
				+ ", menuPath=" + menuPath + ", menuSeq=" + menuSeq
				+ ", menuIcon=" + menuIcon + ", domainCode=" + domainCode
				+ ", domainName=" + domainName + ", state=" + state
				+ ", createDate=" + createDate + ", lastModifyDate="
				+ lastModifyDate + ", lastModifyOperatorId="
				+ lastModifyOperatorId + ", remark=" + remark + ", childMenus="
				+ childMenus + ", isRoot=" + isRoot + ", isLeaf=" + isLeaf
				+ "]";
	}

	public String getMenuType() {
		return menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	public boolean is$$isChecked() {
		return $$isChecked;
	}

	public void set$$isChecked(boolean $$isChecked) {
		this.$$isChecked = $$isChecked;
	}


}
