package com.wo56.business.sys.vo;

// default package
// Generated 2015-11-10 11:36:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SysObjectGrant generated by hbm2java
 */
public class SysObjectGrant implements java.io.Serializable {

	private int objectGrantId;
	private int objectType;
	private long objectId;
	private int entityId;
	private int isPermit;
	private int state;
	private Date createDate;
	private Date modifyDate;
	private long opId;
	private String remark;

	public SysObjectGrant() {
	}

	public int getObjectGrantId() {
		return objectGrantId;
	}

	public void setObjectGrantId(int objectGrantId) {
		this.objectGrantId = objectGrantId;
	}

	public int getObjectType() {
		return objectType;
	}

	public void setObjectType(int objectType) {
		this.objectType = objectType;
	}

	public long getObjectId() {
		return objectId;
	}

	public void setObjectId(long objectId) {
		this.objectId = objectId;
	}

	public int getEntityId() {
		return entityId;
	}

	public void setEntityId(int entityId) {
		this.entityId = entityId;
	}

	public int getIsPermit() {
		return isPermit;
	}

	public void setIsPermit(int isPermit) {
		this.isPermit = isPermit;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public long getOpId() {
		return opId;
	}

	public void setOpId(long opId) {
		this.opId = opId;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
}
