package com.wo56.business.sys.vo;
// default package
// Generated 2015-7-8 15:23:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SysRoleGrant generated by hbm2java
 */
public class SysRoleGrant implements java.io.Serializable {

	private Integer roleGrantId;
	private int roleId;
	private int entityId;
	private int state;
	private Date createDate;
	private Date lastModifyDate;
	private Long lastModifyOperatorId;
	private String remark;

	public SysRoleGrant() {
	}

	public SysRoleGrant(int roleId, int entityId, int state, Date createDate,
			Date lastModifyDate) {
		this.roleId = roleId;
		this.entityId = entityId;
		this.state = state;
		this.createDate = createDate;
		this.lastModifyDate = lastModifyDate;
	}

	public SysRoleGrant(int roleId, int entityId, int state, Date createDate,
			Date lastModifyDate, Long lastModifyOperatorId, String remark) {
		this.roleId = roleId;
		this.entityId = entityId;
		this.state = state;
		this.createDate = createDate;
		this.lastModifyDate = lastModifyDate;
		this.lastModifyOperatorId = lastModifyOperatorId;
		this.remark = remark;
	}

	public Integer getRoleGrantId() {
		return this.roleGrantId;
	}

	public void setRoleGrantId(Integer roleGrantId) {
		this.roleGrantId = roleGrantId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public int getEntityId() {
		return this.entityId;
	}

	public void setEntityId(int entityId) {
		this.entityId = entityId;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Long getLastModifyOperatorId() {
		return this.lastModifyOperatorId;
	}

	public void setLastModifyOperatorId(Long lastModifyOperatorId) {
		this.lastModifyOperatorId = lastModifyOperatorId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
