package com.wo56.business.sys.vo;
// default package
// Generated 2015-7-8 15:21:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.framework.core.base.POJO;

/**
 * SysRole generated by hbm2java
 */
public class SysRole extends POJO {

	private Integer roleId;
	private String roleName;
	private int state;
	private Date lastModifyDate;
	private Long lastModifyOperatorId;
	private String remark;
	private Integer orgId;
	private int roleType;
	//private Long tenantId;
	private String tenantCode;
	private Integer menuType;//角色赋权对应的菜单的类型，1 平台的菜单，2 专线 3 商家
	
	

	public SysRole() {
	}

	public SysRole(String roleName, int state, Date createDate,
			Date lastModifyDate) {
		this.roleName = roleName;
		this.state = state;
		this.createDate = createDate;
		this.lastModifyDate = lastModifyDate;
	}

	public SysRole(String roleName, int state, Date createDate,
			Date lastModifyDate, Long lastModifyOperatorId, String remark) {
		this.roleName = roleName;
		this.state = state;
		this.createDate = createDate;
		this.lastModifyDate = lastModifyDate;
		this.lastModifyOperatorId = lastModifyOperatorId;
		this.remark = remark;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Long getLastModifyOperatorId() {
		return this.lastModifyOperatorId;
	}

	public void setLastModifyOperatorId(Long lastModifyOperatorId) {
		this.lastModifyOperatorId = lastModifyOperatorId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	
	public Integer getOrgId() {
		return orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	public int getRoleType() {
		return roleType;
	}

	public void setRoleType(int roleType) {
		this.roleType = roleType;
	}
	

	public Long getTenantId() {
		return tenantId;
	}

	public void setTenantId(Long tenantId) {
		this.tenantId = tenantId;
	}
	

	public String getTenantCode() {
		return tenantCode;
	}

	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	@Override
	public String toString() {
		return "SysRole [roleId=" + roleId + ", roleName=" + roleName
				+ ", state=" + state + ", createDate=" + createDate
				+ ", lastModifyDate=" + lastModifyDate
				+ ", lastModifyOperatorId=" + lastModifyOperatorId
				+ ", remark=" + remark + "]";
	}

	public Integer getMenuType() {
		return menuType;
	}

	public void setMenuType(Integer menuType) {
		this.menuType = menuType;
	}

	
	
}
