package com.wo56.business.sys.vo;
// default package
// Generated 2015-7-8 15:25:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SysRoleOperRel generated by hbm2java
 */
public class SysRoleOperRel implements java.io.Serializable {

	private int roleOperId;
	private int roleId;
	private long operatorId;
	private int state;
	private Date createDate;
	private Date lastModifyDate;
	private Long lastModifyOperatorId;
	private String remark;

	public SysRoleOperRel() {
	}

	public SysRoleOperRel(int roleOperId, int roleId, long operatorId,
			int state, Date createDate, Date lastModifyDate) {
		this.roleOperId = roleOperId;
		this.roleId = roleId;
		this.operatorId = operatorId;
		this.state = state;
		this.createDate = createDate;
		this.lastModifyDate = lastModifyDate;
	}

	public SysRoleOperRel(int roleOperId, int roleId, long operatorId,
			int state, Date createDate, Date lastModifyDate,
			Long lastModifyOperatorId, String remark) {
		this.roleOperId = roleOperId;
		this.roleId = roleId;
		this.operatorId = operatorId;
		this.state = state;
		this.createDate = createDate;
		this.lastModifyDate = lastModifyDate;
		this.lastModifyOperatorId = lastModifyOperatorId;
		this.remark = remark;
	}

	public int getRoleOperId() {
		return this.roleOperId;
	}

	public void setRoleOperId(int roleOperId) {
		this.roleOperId = roleOperId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(long operatorId) {
		this.operatorId = operatorId;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Long getLastModifyOperatorId() {
		return this.lastModifyOperatorId;
	}

	public void setLastModifyOperatorId(Long lastModifyOperatorId) {
		this.lastModifyOperatorId = lastModifyOperatorId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
