package com.wo56.business.sys.vo;
// Generated 2017-3-27 11:03:25 by Hibernate Tools 3.4.0.CR1

/**
 * SysTableHeadConfig generated by hbm2java
 */
public class SysTableHeadConfig implements java.io.Serializable {

	private Integer id;
	private long tenantId;
	private long orgId;
	private long userId;
	private String tableName;
	private String headName;
	private String headCode;
	private int headIndex;
	private int state;

	public SysTableHeadConfig() {
	}

	public SysTableHeadConfig(long tenantId, long orgId, long userId, String tableName, String headName, String headCode,
			int headIndex, int state) {
		this.tenantId = tenantId;
		this.orgId = orgId;
		this.userId = userId;
		this.tableName = tableName;
		this.headName = headName;
		this.headCode = headCode;
		this.headIndex = headIndex;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public long getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(long tenantId) {
		this.tenantId = tenantId;
	}

	public long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(long orgId) {
		this.orgId = orgId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getHeadName() {
		return this.headName;
	}

	public void setHeadName(String headName) {
		this.headName = headName;
	}

	public String getHeadCode() {
		return this.headCode;
	}

	public void setHeadCode(String headCode) {
		this.headCode = headCode;
	}

	public int getHeadIndex() {
		return this.headIndex;
	}

	public void setHeadIndex(int headIndex) {
		this.headIndex = headIndex;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
