package com.wo56.business.sys.vo;

// Generated 2016-7-5 15:08:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.framework.core.base.POJO;

/**
 * TenantDef generated by hbm2java
 */
public class SysTenantDef extends POJO implements java.io.Serializable {

	//private long tenantId;
	private String tenantCode;
	private String name;
	private String linkMan;
	private String linkPhone;
	private String outerLinkMan;
	private String outerLinkPhone;
	private String csPhones;
	private String domain;
	private String style;
	//private Date createDate;
	private int status;

	public SysTenantDef() {
	}

	public SysTenantDef(long tenantId, Date createDate) {
		this.tenantId = tenantId;
		this.createDate = createDate;
	}

	public SysTenantDef(long tenantId, String tenantCode, String name,
			String linkMan, String linkPhone, String outerLinkMan,
			String outerLinkPhone, String csPhones, String domain,
			String style, Date createDate, int status) {
		this.tenantId = tenantId;
		this.tenantCode = tenantCode;
		this.name = name;
		this.linkMan = linkMan;
		this.linkPhone = linkPhone;
		this.outerLinkMan = outerLinkMan;
		this.outerLinkPhone = outerLinkPhone;
		this.csPhones = csPhones;
		this.domain = domain;
		this.style = style;
		this.createDate = createDate;
		this.status = status;
	}

	public Long getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(long tenantId) {
		this.tenantId = tenantId;
	}

	public String getTenantCode() {
		return this.tenantCode;
	}

	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLinkMan() {
		return this.linkMan;
	}

	public void setLinkMan(String linkMan) {
		this.linkMan = linkMan;
	}

	public String getLinkPhone() {
		return this.linkPhone;
	}

	public void setLinkPhone(String linkPhone) {
		this.linkPhone = linkPhone;
	}

	public String getOuterLinkMan() {
		return this.outerLinkMan;
	}

	public void setOuterLinkMan(String outerLinkMan) {
		this.outerLinkMan = outerLinkMan;
	}

	public String getOuterLinkPhone() {
		return this.outerLinkPhone;
	}

	public void setOuterLinkPhone(String outerLinkPhone) {
		this.outerLinkPhone = outerLinkPhone;
	}

	public String getCsPhones() {
		return this.csPhones;
	}

	public void setCsPhones(String csPhones) {
		this.csPhones = csPhones;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
