var fileId,fileUrl,fileImg,fileColse,definedImg,fileJdt,callbackUrl;function onClick(a,b,d,c,e,f,h){this.fileId=a;this.fileUrl=b;this.fileImg=d;this.fileColse=c;this.definedImg=e;this.fileJdt=f;this.callbackUrl=h;a=document.getElementById("file");window.ActiveXObject?a.click():(b=document.createEvent("MouseEvents"),b.initEvent("click",!0,!0),a.dispatchEvent(b))}
function operation(){var a=document.getElementById("file").value;if(null!=a&&void 0!=a&&""!=a){openJdt();document.getElementById("uploadFrom");a=a.substr(a.lastIndexOf(".")).toLowerCase();if(0>".gif,.jpg,.png,.jpeg,.ico,".indexOf(a+","))return closeJdt(),alert("上传图片格式不正确！"),!1;if(checkProperty(document.getElementById("file")))return getFromObj().action="attach.ajax?cmd=doUpload",postForm(getFromObj(),function(a){closeJdt();window.parent.document.getElementById(fileId).value=a;queryFile(a,this.fileId,
this.fileUrl,this.fileImg,this.fileColse,this.definedImg)},!1),!0}return!1}
function delFile(a,b,d,c,e,f,h){null!=a&&void 0!=a&&""!=a&&(openJdt(),doPost("attach.ajax?cmd=doDel&flowId="+a,function(a){null!=f&&void 0!=f&&""!=f&&"null"!=f&&"undefined"!=f?window.parent.document.getElementById(c).src=getRootPath()+f:window.parent.document.getElementById(c).src=getRootPath()+"/image/fa.jpg";window.parent.document.getElementById(b).value="";window.parent.document.getElementById(d).value="";closeJdt()},!1))}
function queryFile(a,b,d,c,e,f,h){this.fileId=b;this.fileUrl=d;this.fileImg=c;this.fileColse=e;this.definedImg=f;if(null!=a&&void 0!=a&&""!=a){openJdt();var g=this;doPost("attach.ajax?cmd=doQuery&_GRID_TYPE=jq&flowIds="+a,function(e){e=JSON.parse(e);0<e.total?(window.parent.document.getElementById(b).value=a,window.parent.document.getElementById(c).src=e.rows[0].fullPathUrl,window.parent.document.getElementById(d).value=e.rows[0].storePath,null!=g.callbackUrl&&void 0!=g.callbackUrl&&""!=g.callbackUrl&&
doPost(g.callbackUrl+"&flowIds="+a,null,!1)):(window.parent.document.getElementById(b).value="",window.parent.document.getElementById(d).value="");closeJdt()},!1)}else window.parent.document.getElementById(e).style.display="none",window.parent.document.getElementById(b).value="",window.parent.document.getElementById(d).value=""}function openJdt(){null!=this.fileJdt&&void 0!=this.fileJdt&&""!=this.fileJdt&&(window.parent.document.getElementById(this.fileJdt).style.display="block")}
function closeJdt(){null!=this.fileJdt&&void 0!=this.fileJdt&&""!=this.fileJdt&&(window.parent.document.getElementById(this.fileJdt).style.display="none")}function getFromObj(){return document.getElementById("uploadFrom")}
function checkProperty(a){var b=0,d=/msie/i.test(navigator.userAgent)&&!window.opera;try{if(d&&!a.files)var c=a.value,b=(new ActiveXObject("Scripting.FileSystemObject")).GetFile(c).Size;else b=a.files[0].size;b=Math.round(b/1024*100)/100;b=Math.ceil(b);if(1024<b)return closeJdt(),alert("上传图片为"+b+"KB，图片最大为1024KB，请重新上传!"),!1}catch(e){}return!0}
function doPost(a,b,d){var c=[];a=parseUrlParam(a,c);0<c.length&&(a+="&"+c.sort().join("&"));a=a+"&sign="+md5(a+getCookie("token"));$.ajax({url:a,type:"POST",dataType:"text",success:function(a,c){d?alert(a):0<=a.indexOf("javascript:")&&eval(a);"function"==typeof b?b(a):"string"==typeof b&&eval(b)},error:function(a,b,c){a=/<body>(.*)<\/body>/g.exec(a.responseText.replace(/\r\n/g,""));alert(a[1].trim())}})}
function getJson(a){var b={},d=[];d.push("_GRID_TYPE=jq");b._GRID_TYPE="jq";var c;c=a instanceof jQuery?a.serialize():$(a).serialize();c=c.replace(/\+/g," ");c=c.split("&");var e,f;a=parseUrlParam(a.action,d);$.each(c,function(a,c){""!==c&&(d.push(c),c=c.split("="),e=decodeURIComponent(c[0]),f=decodeURIComponent(c[1]),b[e]=b[e]?b[e].concat(",").concat(f):f)});0<d.length&&(a+="&"+d.sort().join("&"));b.sign=md5(a+getCookie("token"));return b}
function parseUrlParam(a,b){var d="";if(void 0!=a){var c=a.substring(a.lastIndexOf("/")+1);if(0<(idx=c.indexOf("&"))){var d=c.substring(0,idx),c=c.substring(idx+1).split("&"),e;for(e in c)"null"!==c[e].split("=")[1]&&""!==c[e].split("=")[1]&&b.push(c[e])}else d=c}return d}function getCookie(a){var b;return(b=document.cookie.match(new RegExp("(^| )"+a+"=([^;]*)(;|$)")))?unescape(b[2]):""}
function postForm(a,b,d,c,e,f){"string"==typeof a&&(a=document.getElementById(a));a instanceof jQuery&&(jqForm=a,a=jqForm[0],a.action=jqForm.action);"undefined"==typeof d&&(d=!0);a.method="POST";-1==a.encoding.indexOf("multipart")?$.ajax({url:a.action,type:a.method,dataType:"text",data:getJson(a),success:function(a,c){setTimeout(function(){},200);d?alert(a):0<=a.indexOf("javascript:")&&eval(a);"function"==typeof b?b(a):"string"==typeof b&&eval(b)},error:function(a,b,c){a=/<body>(.*)<\/body>/g.exec(a.responseText.replace(/\r\n/g,
""));alert(a[1].trim());null!=e&&void 0!=e&&(e.disabled="",e.value=f)}}):$.ajaxFileUpload({url:a.action,secureuri:!1,fileElementId:"file",dataType:"text",data:getJson(a),success:function(a,c){a=""+a;setTimeout(function(){},200);d?alert(a):0<=a.indexOf("javascript:")&&eval(a);"function"==typeof b?b(a):"string"==typeof b&&eval(b)},error:function(a,b,c){alert("文件上传失败!")}})};
