package com.wo56.business.org.vo;

// Generated 2016-6-8 16:29:12 by Hibernate Tools 3.4.0.CR1

import com.framework.core.base.POJO;

/**
 * Organization generated by hbm2java
 */
public class Organization extends POJO{

	private long orgId;
	private String orgCode;
	private String orgName;
	private String orgShorter;
	private String parentOrgCode;
	private long parentOrgId;
	private String provinceName;
	private String provinceId;
	private String regionName;
	private String regionId;
	private String countyName;
	private String countyId;
	private String departmentAddress;
	private String longitude;
	private String latitude;
	private String acceptLinkPhone;
	private String carryLinkPhone;
	private String orgManager;
	private Integer orgType;
	private String orgPrincipal;
	private String orgPrincipalPhone;
	private String fax;
	private String supportStaff;
	private String supportStaffPhone;
	private Integer businessType;
	private int isDepartment;
	private Integer isPaymentCollection;
	private Long limitForCollection;
	private Integer isSettleDocket;
	private Integer currencyType;
	private String cashReference;
	private Long lockLimit;
	private Long warningLimit;
	private Integer managementCos;
	private String remark;
	//private Long tenantId;
	private String tenantType;
	private Integer state;
	private String busiNotes;
	private String sellerNotes;
	private String streetName;
	private String streetId;
	private String supportStaff2;
	private String supportStaffPhone2;
	private String corporateBackCard;
	private String corporateFrontCard;
	private String businesslicensePic;
	private Long creatorId;
	
	public Long getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}


	public String getSupportStaff2() {
		return supportStaff2;
	}

	public void setSupportStaff2(String supportStaff2) {
		this.supportStaff2 = supportStaff2;
	}

	public String getSupportStaffPhone2() {
		return supportStaffPhone2;
	}

	public void setSupportStaffPhone2(String supportStaffPhone2) {
		this.supportStaffPhone2 = supportStaffPhone2;
	}

	public String getStreetName() {
		return streetName;
	}

	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	public String getStreetId() {
		return streetId;
	}

	public void setStreetId(String streetId) {
		this.streetId = streetId;
	}

	public Organization() {
	}

	public Organization(long parentOrgId, int isDepartment) {
		this.parentOrgId = parentOrgId;
		this.isDepartment = isDepartment;
	}

	public Organization(String orgCode, String orgName, String orgShorter,
			String parentOrgCode, long parentOrgId, String provinceName,
			String provinceId, String regionName, String regionId,
			String countyName, String countyId, String departmentAddress,
			String longitude, String latitude, String acceptLinkPhone,
			String carryLinkPhone, String orgManager, Integer orgType,
			String orgPrincipal, String orgPrincipalPhone, String fax,
			String supportStaff, String supportStaffPhone,
			Integer businessType, int isDepartment,
			Integer isPaymentCollection, Long limitForCollection,
			Integer isSettleDocket, Integer currencyType, String cashReference,
			Long lockLimit, Long warningLimit, Integer managementCos,
			String remark, Long tenantId, String tenantCode, 
			Integer state, String busiNotes,String sellerNotes,String streetName,String streetId) {
		this.orgCode = orgCode;
		this.orgName = orgName;
		this.orgShorter = orgShorter;
		this.parentOrgCode = parentOrgCode;
		this.parentOrgId = parentOrgId;
		this.provinceName = provinceName;
		this.provinceId = provinceId;
		this.regionName = regionName;
		this.regionId = regionId;
		this.countyName = countyName;
		this.countyId = countyId;
		this.departmentAddress = departmentAddress;
		this.longitude = longitude;
		this.latitude = latitude;
		this.acceptLinkPhone = acceptLinkPhone;
		this.carryLinkPhone = carryLinkPhone;
		this.orgManager = orgManager;
		this.orgType = orgType;
		this.orgPrincipal = orgPrincipal;
		this.orgPrincipalPhone = orgPrincipalPhone;
		this.fax = fax;
		this.supportStaff = supportStaff;
		this.supportStaffPhone = supportStaffPhone;
		this.businessType = businessType;
		this.isDepartment = isDepartment;
		this.isPaymentCollection = isPaymentCollection;
		this.limitForCollection = limitForCollection;
		this.isSettleDocket = isSettleDocket;
		this.currencyType = currencyType;
		this.cashReference = cashReference;
		this.lockLimit = lockLimit;
		this.warningLimit = warningLimit;
		this.managementCos = managementCos;
		this.remark = remark;
		this.tenantId = tenantId;
		this.state = state;
		this.busiNotes = busiNotes;
		this.sellerNotes = sellerNotes;
		this.streetName = streetName;
		this.streetId = streetId;
		
	}

	public long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(long orgId) {
		this.orgId = orgId;
	}

	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getOrgShorter() {
		return this.orgShorter;
	}

	public void setOrgShorter(String orgShorter) {
		this.orgShorter = orgShorter;
	}

	public String getParentOrgCode() {
		return this.parentOrgCode;
	}

	public void setParentOrgCode(String parentOrgCode) {
		this.parentOrgCode = parentOrgCode;
	}

	public long getParentOrgId() {
		return this.parentOrgId;
	}

	public void setParentOrgId(long parentOrgId) {
		this.parentOrgId = parentOrgId;
	}

	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	public String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	public String getCountyName() {
		return this.countyName;
	}

	public void setCountyName(String countyName) {
		this.countyName = countyName;
	}

	public String getCountyId() {
		return this.countyId;
	}

	public void setCountyId(String countyId) {
		this.countyId = countyId;
	}

	public String getDepartmentAddress() {
		return this.departmentAddress;
	}

	public void setDepartmentAddress(String departmentAddress) {
		this.departmentAddress = departmentAddress;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getAcceptLinkPhone() {
		return this.acceptLinkPhone;
	}

	public void setAcceptLinkPhone(String acceptLinkPhone) {
		this.acceptLinkPhone = acceptLinkPhone;
	}

	public String getCarryLinkPhone() {
		return this.carryLinkPhone;
	}

	public void setCarryLinkPhone(String carryLinkPhone) {
		this.carryLinkPhone = carryLinkPhone;
	}

	public String getOrgManager() {
		return this.orgManager;
	}

	public void setOrgManager(String orgManager) {
		this.orgManager = orgManager;
	}

	public Integer getOrgType() {
		return this.orgType;
	}

	public void setOrgType(Integer orgType) {
		this.orgType = orgType;
	}

	public String getOrgPrincipal() {
		return this.orgPrincipal;
	}

	public void setOrgPrincipal(String orgPrincipal) {
		this.orgPrincipal = orgPrincipal;
	}

	public String getOrgPrincipalPhone() {
		return this.orgPrincipalPhone;
	}

	public void setOrgPrincipalPhone(String orgPrincipalPhone) {
		this.orgPrincipalPhone = orgPrincipalPhone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getSupportStaff() {
		return this.supportStaff;
	}

	public void setSupportStaff(String supportStaff) {
		this.supportStaff = supportStaff;
	}

	public String getSupportStaffPhone() {
		return this.supportStaffPhone;
	}

	public void setSupportStaffPhone(String supportStaffPhone) {
		this.supportStaffPhone = supportStaffPhone;
	}

	public Integer getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(Integer businessType) {
		this.businessType = businessType;
	}

	public int getIsDepartment() {
		return this.isDepartment;
	}

	public void setIsDepartment(int isDepartment) {
		this.isDepartment = isDepartment;
	}

	public Integer getIsPaymentCollection() {
		return this.isPaymentCollection;
	}

	public void setIsPaymentCollection(Integer isPaymentCollection) {
		this.isPaymentCollection = isPaymentCollection;
	}

	public Long getLimitForCollection() {
		return this.limitForCollection;
	}

	public void setLimitForCollection(Long limitForCollection) {
		this.limitForCollection = limitForCollection;
	}

	public Integer getIsSettleDocket() {
		return this.isSettleDocket;
	}

	public void setIsSettleDocket(Integer isSettleDocket) {
		this.isSettleDocket = isSettleDocket;
	}

	public Integer getCurrencyType() {
		return this.currencyType;
	}

	public void setCurrencyType(Integer currencyType) {
		this.currencyType = currencyType;
	}

	public String getCashReference() {
		return this.cashReference;
	}

	public void setCashReference(String cashReference) {
		this.cashReference = cashReference;
	}

	public Long getLockLimit() {
		return this.lockLimit;
	}

	public void setLockLimit(Long lockLimit) {
		this.lockLimit = lockLimit;
	}

	public Long getWarningLimit() {
		return this.warningLimit;
	}

	public void setWarningLimit(Long warningLimit) {
		this.warningLimit = warningLimit;
	}

	public Integer getManagementCos() {
		return this.managementCos;
	}

	public void setManagementCos(Integer managementCos) {
		this.managementCos = managementCos;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Long getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(Long tenantId) {
		this.tenantId = tenantId;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getTenantType() {
		return tenantType;
	}

	public void setTenantType(String tenantType) {
		this.tenantType = tenantType;
	}
	public String getBusiNotes() {
		return this.busiNotes;
	}

	public void setBusiNotes(String busiNotes) {
		this.busiNotes = busiNotes;
	}

	public String getSellerNotes() {
		return this.sellerNotes;
	}

	public void setSellerNotes(String sellerNotes) {
		this.sellerNotes = sellerNotes;
	}

	public String getCorporateBackCard() {
		return corporateBackCard;
	}

	public void setCorporateBackCard(String corporateBackCard) {
		this.corporateBackCard = corporateBackCard;
	}

	public String getCorporateFrontCard() {
		return corporateFrontCard;
	}

	public void setCorporateFrontCard(String corporateFrontCard) {
		this.corporateFrontCard = corporateFrontCard;
	}

	public String getBusinesslicensePic() {
		return businesslicensePic;
	}

	public void setBusinesslicensePic(String businesslicensePic) {
		this.businesslicensePic = businesslicensePic;
	}


}
