/**
 * Created with JetBrains PhpStorm.
 * User: xuheng
 * Date: 12-8-8
 * Time: 涓嫔崃2:00
 * To change this template use File | Settings | File Templates.
 */
var templates = [
    {
        "pre":"pre0.png",
        'title':lang.blank,
        'preHtml':'<p class="ue_t">&nbsp;娆㈣繋浣跨敤UEditor锛?/p>',
        "html":'<p class="ue_t">娆㈣繋浣跨敤UEditor锛?/p>'

    },
    {
        "pre":"pre1.png",
        'title':lang.blog,
        'preHtml':'<h1 label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">娣卞叆鐞呜ВRange</span></h1><p style="text-align:center;"><strong class=" ">UEditor浜屾寮€鍙?/strong></p><h3><span class=" " style="font-family:骞煎浑">浠€涔堟槸Range</span></h3><p style="text-indent:2em;">瀵逛簬钬沧彃鍏モ€濋€夐」鍗′笂镄勫簱锛屽湪璁捐镞堕兘鍏呭垎钥冭槛浜嗗叾涓殑椤逛笌鏂囨。鏁翠綋澶栬镄勫岗璋冩€с€?</p><br /><h3><span class=" " style="font-family:骞煎浑">Range鑳藉共浠€涔?/span></h3><p style="text-indent:2em;">鍦ㄢ€滃紑濮嬧€濋€夐」鍗′笂锛岄€氲绷浠庡揩阃熸牱寮忓簱涓负镓€阃夋枃链€夋嫨涓€绉嶅瑙傦紝镇ㄥ彲浠ユ柟渚垮湴镟存敼鏂囨。涓墍阃夋枃链殑镙煎纺銆?/p>',
        "html":'<h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">[阌叆鏂囨。镙囬]</span></h1><p style="text-align:center;"><strong class="ue_t">[阌叆鏂囨。鍓爣棰榏</strong></p><h3><span class="ue_t" style="font-family:骞煎浑">[镙囬 1]</span></h3><p class="ue_t"  style="text-indent:2em;">瀵逛簬钬沧彃鍏モ€濋€夐」鍗′笂镄勫簱锛屽湪璁捐镞堕兘鍏呭垎钥冭槛浜嗗叾涓殑椤逛笌鏂囨。鏁翠綋澶栬镄勫岗璋冩€с€?镇ㄥ彲浠ヤ娇鐢ㄨ繖浜涘簱鏉ユ彃鍏ヨ〃镙笺€侀〉鐪夈€侀〉鑴氥€佸垪琛ㄣ€佸皝闱互鍙婂叾浠栨枃妗ｆ瀯寤哄熀鍧椼€?镇ㄥ垱寤虹殑锲剧墖銆佸浘琛ㄦ垨鍏崇郴锲句篃灏嗕笌褰揿墠镄勬枃妗ｅ瑙傚岗璋冧竴镊淬€?/p><h3><span class="ue_t" style="font-family:骞煎浑">[镙囬 2]</span></h3><p class="ue_t"  style="text-indent:2em;">鍦ㄢ€滃紑濮嬧€濋€夐」鍗′笂锛岄€氲绷浠庡揩阃熸牱寮忓簱涓负镓€阃夋枃链€夋嫨涓€绉嶅瑙傦紝镇ㄥ彲浠ユ柟渚垮湴镟存敼鏂囨。涓墍阃夋枃链殑镙煎纺銆?镇ㄨ缮鍙互浣跨敤钬滃紑濮嬧€濋€夐」鍗′笂镄勫叾浠栨带浠舵潵鐩存帴璁剧疆鏂囨湰镙煎纺銆傚ぇ澶氭暟鎺т欢閮藉厑璁告偍阃夋嫨鏄娇鐢ㄥ綋鍓崭富棰桦瑙傦紝杩樻槸浣跨敤镆愮鐩存帴鎸囧畾镄勬牸寮忋€?</p><h3><span class="ue_t" style="font-family:骞煎浑">[镙囬 3]</span></h3><p class="ue_t">瀵逛簬钬沧彃鍏モ€濋€夐」鍗′笂镄勫簱锛屽湪璁捐镞堕兘鍏呭垎钥冭槛浜嗗叾涓殑椤逛笌鏂囨。鏁翠綋澶栬镄勫岗璋冩€с€?镇ㄥ彲浠ヤ娇鐢ㄨ繖浜涘簱鏉ユ彃鍏ヨ〃镙笺€侀〉鐪夈€侀〉鑴氥€佸垪琛ㄣ€佸皝闱互鍙婂叾浠栨枃妗ｆ瀯寤哄熀鍧椼€?镇ㄥ垱寤虹殑锲剧墖銆佸浘琛ㄦ垨鍏崇郴锲句篃灏嗕笌褰揿墠镄勬枃妗ｅ瑙傚岗璋冧竴镊淬€?/p><p class="ue_t"><br /></p>'

    },
    {
        "pre":"pre2.png",
        'title':lang.resume,
        'preHtml':'<h1 label="Title left" name="tl" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;"><span style="color:#e36c09;" class=" ">WEB鍓岖寮€鍙戠亩铡?/span></h1><table width="100%" border="1" bordercolor="#95B3D7" style="border-collapse:collapse;"><tbody><tr><td width="100" style="text-align:center;"><p><span style="background-color:transparent;">鎻?/span><br /></p><p>鍏?/p><p>镦?/p><p>鐗?/p></td><td><p><span style="background-color:transparent;"> 鑱旗郴鐢佃瘽锛?/span><span class="ue_t" style="background-color:transparent;">[阌叆镇ㄧ殑鐢佃瘽]</span><br /></p><p><span style="background-color:transparent;"> 鐢靛瓙闾欢锛?/span><span class="ue_t" style="background-color:transparent;">[阌叆镇ㄧ殑鐢靛瓙闾欢鍦板潃]</span><br /></p><p><span style="background-color:transparent;"> 瀹跺涵浣忓潃锛?/span><span class="ue_t" style="background-color:transparent;">[阌叆镇ㄧ殑鍦板潃]</span><br /></p></td></tr></tbody></table><h3><span style="color:#E36C09;font-size:20px;">鐩爣鑱屼綅</span></h3><p style="text-indent:2em;" class=" ">WEB鍓岖镰斿彂宸ョ▼甯?/p><h3><span style="color:#e36c09;font-size:20px;">瀛﹀巻</span></h3><p><span style="display:none;line-height:0px;" id="_baidu_bookmark_start_26">锘?/span></p><ol style="list-style-type:decimal;"><li><p><span class="ue_t">[璧锋镞堕棿]</span> <span class="ue_t">[瀛︽牎鍚岖О] </span> <span class="ue_t">[镓€瀛︿笓涓歖</span> <span class="ue_t">[镓€銮峰浣峕</span></p></li></ol><h3><span style="color:#e36c09;font-size:20px;" class="ue_t">宸ヤ綔缁忛獙</span></h3><p><br /></p>',
        "html":'<h1 label="Title left" name="tl" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;"><span style="color:#e36c09;" class="ue_t">[姝ゅ阌叆绠€铡嗘爣棰榏</span></h1><p><span style="color:#e36c09;"><br /></span></p><table width="100%" border="1" bordercolor="#95B3D7" style="border-collapse:collapse;"><tbody><tr><td width="200" style="text-align:center;" class="ue_t">銆愭澶勬彃鍏ョ収鐗囥€?/td><td><p><br /></p><p> 鑱旗郴鐢佃瘽锛?span class="ue_t">[阌叆镇ㄧ殑鐢佃瘽]</span></p><p><br /></p><p> 鐢靛瓙闾欢锛?span class="ue_t">[阌叆镇ㄧ殑鐢靛瓙闾欢鍦板潃]</span></p><p><br /></p><p> 瀹跺涵浣忓潃锛?span class="ue_t">[阌叆镇ㄧ殑鍦板潃]</span></p><p><br /></p></td></tr></tbody></table><h3><span style="color:#e36c09;font-size:20px;">鐩爣鑱屼綅</span></h3><p style="text-indent:2em;" class="ue_t">[姝ゅ阌叆镇ㄧ殑链熸湜鑱屼綅]</p><h3><span style="color:#e36c09;font-size:20px;">瀛﹀巻</span></h3><p><span style="display:none;line-height:0px;" id="_baidu_bookmark_start_26">锘?/span></p><ol style="list-style-type:decimal;"><li><p><span class="ue_t">[阌叆璧锋镞堕棿]</span> <span class="ue_t">[阌叆瀛︽牎鍚岖О] </span> <span class="ue_t">[阌叆镓€瀛︿笓涓歖</span> <span class="ue_t">[阌叆镓€銮峰浣峕</span></p></li><li><p><span class="ue_t">[阌叆璧锋镞堕棿]</span> <span class="ue_t">[阌叆瀛︽牎鍚岖О]</span> <span class="ue_t">[阌叆镓€瀛︿笓涓歖</span> <span class="ue_t">[阌叆镓€銮峰浣峕</span></p></li></ol><h3><span style="color:#e36c09;font-size:20px;" class="ue_t">宸ヤ綔缁忛獙</span></h3><ol style="list-style-type:decimal;"><li><p><span class="ue_t">[阌叆璧锋镞堕棿]</span> <span class="ue_t">[阌叆鍏徃鍚岖О]</span> <span class="ue_t">[阌叆鑱屼綅鍚岖О]</span> </p></li><ol style="list-style-type:lower-alpha;"><li><p><span class="ue_t">[阌叆璐熻矗椤圭洰]</span> <span class="ue_t">[阌叆椤圭洰绠€浠媇</span></p></li><li><p><span class="ue_t">[阌叆璐熻矗椤圭洰]</span> <span class="ue_t">[阌叆椤圭洰绠€浠媇</span></p></li></ol><li><p><span class="ue_t">[阌叆璧锋镞堕棿]</span> <span class="ue_t">[阌叆鍏徃鍚岖О]</span> <span class="ue_t">[阌叆鑱屼綅鍚岖О]</span> </p></li><ol style="list-style-type:lower-alpha;"><li><p><span class="ue_t">[阌叆璐熻矗椤圭洰]</span> <span class="ue_t">[阌叆椤圭洰绠€浠媇</span></p></li></ol></ol><p><span style="color:#e36c09;font-size:20px;">鎺屾汇鎶€鑳?/span></p><p style="text-indent:2em;"> &nbsp;<span class="ue_t">[杩欓噷鍙互阌叆镇ㄦ墍鎺屾汇镄勬妧鑳絔</span><br /></p>'

    },
    {
        "pre":"pre3.png",
        'title':lang.richText,
        'preHtml':'<h1 label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;" class="ue_t">[姝ゅ阌叆鏂囩珷镙囬]</h1><p><img src="http://img.baidu.com/hi/youa/y_0034.gif" width="150" height="100" border="0" hspace="0" vspace="0" style="width:150px;height:100px;float:left;" />锲炬枃娣锋帓鏂规硶</p><p>锲剧墖灞呭乏锛屾枃瀛楀洿缁曞浘鐗囨帓鐗?/p><p>鏂规硶锛氩湪鏂囧瓧鍓嶉溃鎻掑叆锲剧墖锛岃缃眳宸﹀榻愶紝铹跺悗鍗冲彲鍦ㄥ彸杈硅緭鍏ュ琛屾枃</p><p><br /></p><p><img src="http://img.baidu.com/hi/youa/y_0040.gif" width="100" height="100" border="0" hspace="0" vspace="0" style="width:100px;height:100px;float:right;" /></p><p>杩樻湁娌℃湁浠€涔埚叾浠栫殑鐜粫鏂瑰纺锻紵杩欓噷鏄眳鍙崇幆缁?/p><p><br /></p><p>娆㈣繋澶у澶氩灏濊瘯锛屼负UEditor鎻愪緵镟村楂樿川閲忔ā鏉匡紒</p>',
        "html":'<p><br /></p><h1 label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;" class="ue_t">[姝ゅ阌叆鏂囩珷镙囬]</h1><p><img src="http://img.baidu.com/hi/youa/y_0034.gif" width="300" height="200" border="0" hspace="0" vspace="0" style="width:300px;height:200px;float:left;" />锲炬枃娣锋帓鏂规硶</p><p>1. 锲剧墖灞呭乏锛屾枃瀛楀洿缁曞浘鐗囨帓鐗?/p><p>鏂规硶锛氩湪鏂囧瓧鍓嶉溃鎻掑叆锲剧墖锛岃缃眳宸﹀榻愶紝铹跺悗鍗冲彲鍦ㄥ彸杈硅緭鍏ュ琛屾枃链?/p><p><br /></p><p>2. 锲剧墖灞呭彸锛屾枃瀛楀洿缁曞浘鐗囨帓鐗?/p><p>鏂规硶锛氩湪鏂囧瓧鍓嶉溃鎻掑叆锲剧墖锛岃缃眳鍙冲榻愶紝铹跺悗鍗冲彲鍦ㄥ乏杈硅緭鍏ュ琛屾枃链?/p><p><br /></p><p>3. 锲剧墖灞呬腑鐜粫鎺掔増</p><p>鏂规硶锛氢翰锛岃繖涓湡蹇冩病链夊姙娉曘€伞€伞€?/p><p><br /></p><p><br /></p><p><img src="http://img.baidu.com/hi/youa/y_0040.gif" width="300" height="300" border="0" hspace="0" vspace="0" style="width:300px;height:300px;float:right;" /></p><p>杩樻湁娌℃湁浠€涔埚叾浠栫殑鐜粫鏂瑰纺锻紵杩欓噷鏄眳鍙崇幆缁?/p><p><br /></p><p>娆㈣繋澶у澶氩灏濊瘯锛屼负UEditor鎻愪緵镟村楂樿川閲忔ā鏉匡紒</p><p><br /></p><p>鍗犱綅</p><p><br /></p><p>鍗犱綅</p><p><br /></p><p>鍗犱綅</p><p><br /></p><p>鍗犱綅</p><p><br /></p><p>鍗犱綅</p><p><br /></p><p><br /></p>'
    },
    {
        "pre":"pre4.png",
        'title':lang.sciPapers,
        'preHtml':'<h2 style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;text-align:center;" class="ue_t">[阌叆鏂囩珷镙囬]</h2><p><strong><span style="font-size:12px;">鎽樿</span></strong><span style="font-size:12px;" class="ue_t">锛氲繖閲屽彲浠ヨ緭鍏ュ緢闀垮緢闀垮緢闀垮緢闀垮緢闀垮緢闀垮緢闀垮緢闀垮緢宸殑鎽樿</span></p><p style="line-height:1.5em;"><strong>镙囬 1</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">杩欓噷鍙互杈揿叆寰埚鍐呭锛屽彲浠ュ浘鏂囨贩鎺掞紝鍙互链夊垪琛ㄧ瓑銆?/span></p><p style="line-height:1.5em;"><strong>镙囬 2</strong></p><ol style="list-style-type:lower-alpha;"><li><p class="ue_t">鍒楄〃 1</p></li><li><p class="ue_t">鍒楄〃 2</p></li><ol style="list-style-type:lower-roman;"><li><p class="ue_t">澶氱骇鍒楄〃 1</p></li><li><p class="ue_t">澶氱骇鍒楄〃 2</p></li></ol><li><p class="ue_t">鍒楄〃 3<br /></p></li></ol><p style="line-height:1.5em;"><strong>镙囬 3</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">鏉ヤ釜鏂囧瓧锲炬枃娣锋帓镄?/span></p><p style="text-indent:2em;"><br /></p>',
        'html':'<h2 style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;text-align:center;" class="ue_t">[阌叆鏂囩珷镙囬]</h2><p><strong><span style="font-size:12px;">鎽樿</span></strong><span style="font-size:12px;" class="ue_t">锛氲繖閲屽彲浠ヨ緭鍏ュ緢闀垮緢闀垮緢闀垮緢闀垮緢闀垮緢闀垮緢闀垮緢闀垮緢宸殑鎽樿</span></p><p style="line-height:1.5em;"><strong>镙囬 1</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">杩欓噷鍙互杈揿叆寰埚鍐呭锛屽彲浠ュ浘鏂囨贩鎺掞紝鍙互链夊垪琛ㄧ瓑銆?/span></p><p style="line-height:1.5em;"><strong>镙囬 2</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">鏉ヤ釜鍒楄〃鐬呯弥锛?/span></p><ol style="list-style-type:lower-alpha;"><li><p class="ue_t">鍒楄〃 1</p></li><li><p class="ue_t">鍒楄〃 2</p></li><ol style="list-style-type:lower-roman;"><li><p class="ue_t">澶氱骇鍒楄〃 1</p></li><li><p class="ue_t">澶氱骇鍒楄〃 2</p></li></ol><li><p class="ue_t">鍒楄〃 3<br /></p></li></ol><p style="line-height:1.5em;"><strong>镙囬 3</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">鏉ヤ釜鏂囧瓧锲炬枃娣锋帓镄?/span></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">杩欓噷鍙互澶氲</span></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">鍙宠竟鏄浘鐗?/span></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">缁濆娌℃湁闂镄勶紝涓崭俊浣犱篃鍙互璇曡瘯鐪?/span></p><p><br /></p>'
    }
];