package com.wo56.business.sche.ord.vo;
// default package
// Generated 2016-8-1 15:00:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * SchedulerFixTask generated by hbm2java
 */
public class SchedulerFixTask implements java.io.Serializable {

	/**   
	 * 维修任务ID.  
	 */
	private Long fixId;

	/**   
	 * 运单号.  
	 */
	private Long trackingNum;

	/**   
	 * 订单号.  
	 */
	private Long orderId;

	/**   
	 * 师傅任务ID.  
	 */
	private Long taskId;

	/**   
	 * 异常ID.  
	 */
	private String exceId;

	/**   
	 * 异常图片.  
	 */
	private String imagePath;

	/**   
	 * 异常图片id.  
	 */
	private String imageId;

	/**   
	 * 维修类型名称.  
	 */
	private String typeName;

	/**   
	 * 维修类型.  
	 */
	private Integer type;

	/**   
	 * 维修状态.  
	 */
	private int state;

	/**   
	 * 维修描述.  
	 */
	private String notes;

	/**   
	 * 创建人ID.  
	 */
	private Long creatorId;

	/**   
	 * 创建人姓名.  
	 */
	private String creatorName;

	/**   
	 * 创建时间.  
	 */
	private Date createDate;

	/**   
	 * 处理结果图片.  
	 */
	private String fixImagePath;

	/**   
	 * 处理图片id.  
	 */
	private String fixImageId;

	/**   
	 * 处理人ID.  
	 */
	private Long dealer;

	/**   
	 * 处理人姓名.  
	 */
	private String dealerName;

	/**   
	 * 处理时间.  
	 */
	private Date dealDate;
	
	private Integer maintainAttr;
	
	private String maintainAttrName;
	private String handleResult;
	
	
	

	public String getHandleResult() {
		return handleResult;
	}

	public void setHandleResult(String handleResult) {
		this.handleResult = handleResult;
	}

	public Integer getMaintainAttr() {
		return maintainAttr;
	}

	public void setMaintainAttr(Integer maintainAttr) {
		this.maintainAttr = maintainAttr;
	}

	public String getMaintainAttrName() {
		return maintainAttrName;
	}

	public void setMaintainAttrName(String maintainAttrName) {
		this.maintainAttrName = maintainAttrName;
	}

	public SchedulerFixTask() {
	}

	public SchedulerFixTask(Long trackingNum, Long orderId, int state) {
		this.trackingNum = trackingNum;
		this.orderId = orderId;
		this.state = state;
	}

	public SchedulerFixTask(Long trackingNum, Long orderId, Long taskId,
			String exceId, String imagePath, String imageId, String typeName,
			Integer type, int state, String notes, Long creatorId,
			String creatorName, Date createDate, String fixImagePath,
			String fixImageId, Long dealer, String dealerName, Date dealDate) {
		this.trackingNum = trackingNum;
		this.orderId = orderId;
		this.taskId = taskId;
		this.exceId = exceId;
		this.imagePath = imagePath;
		this.imageId = imageId;
		this.typeName = typeName;
		this.type = type;
		this.state = state;
		this.notes = notes;
		this.creatorId = creatorId;
		this.creatorName = creatorName;
		this.createDate = createDate;
		this.fixImagePath = fixImagePath;
		this.fixImageId = fixImageId;
		this.dealer = dealer;
		this.dealerName = dealerName;
		this.dealDate = dealDate;
	}

	public Long getFixId() {
		return this.fixId;
	}

	public void setFixId(Long fixId) {
		this.fixId = fixId;
	}

	public Long getTrackingNum() {
		return this.trackingNum;
	}

	public void setTrackingNum(Long trackingNum) {
		this.trackingNum = trackingNum;
	}

	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public Long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	public String getExceId() {
		return this.exceId;
	}

	public void setExceId(String exceId) {
		this.exceId = exceId;
	}

	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public String getImageId() {
		return this.imageId;
	}

	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public String getCreatorName() {
		return this.creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getFixImagePath() {
		return this.fixImagePath;
	}

	public void setFixImagePath(String fixImagePath) {
		this.fixImagePath = fixImagePath;
	}

	public String getFixImageId() {
		return this.fixImageId;
	}

	public void setFixImageId(String fixImageId) {
		this.fixImageId = fixImageId;
	}

	public Long getDealer() {
		return this.dealer;
	}

	public void setDealer(Long dealer) {
		this.dealer = dealer;
	}

	public String getDealerName() {
		return this.dealerName;
	}

	public void setDealerName(String dealerName) {
		this.dealerName = dealerName;
	}

	public Date getDealDate() {
		return this.dealDate;
	}

	public void setDealDate(Date dealDate) {
		this.dealDate = dealDate;
	}

}
